### ISSUE TITLE
3.7+ File Rename Utility Removes File Association Data

### ISSUE THREAD

**Issue by Remnence** [japanesemediamanager/ShokoDesktop#505]
![issue2](https://cloud.githubusercontent.com/assets/1884580/21567746/2668e9fc-ce74-11e6-8286-fca53a1a32bc.PNG)

As you can see from 12 and 13 the file data is missing. It knows there is a file but the information is gone and you can no longer play the file. This happens to any series you rename. MSSQL2014 on local machine.

**Comment by ElementalCrisis** [comment]
Intresting, I think either @RickDB or @da3dsoul was looking into this before, though I thought we fixed it.

**Comment by Remnence** [comment]
I feel as though my MSSQL install is corrupt somehow. I've have nothing but issues since I moved away from MYSQL. I tried creating a new DB in my current install and the issues followed.

**Comment by Remnence** [comment]
Moved to a MYSQL DB and performance is way better but the issue still exists. So it is definitely not just me.

**Comment by CatmanIX** [comment]
I had this issue, it seemed to be caused by a previous version but persists through the new versions if already present. i just gave up trying to find and fix every file and rebuilt my database from scratch.

**Comment by VadAbel** [comment]
I have this issue, the renamer corrupt the database for files who don't need a rename.
Here a log extract for one file
> [2017-01-30 23:58:42:201] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeRenameFile => JMMServiceImplementation.RenameFile Renaming file From (N:\Media\Anime\Under the Dog\Under the Dog - 01 - OVA - [DameDesuYo][www][1280x720][h264][A9A1E388].mkv) to (N:\Media\Anime\Under the Dog\Under the Dog - 01 - OVA - [DameDesuYo][www][1280x720][h264][A9A1E388].mkv)....

> [2017-01-30 23:58:42:201] Info|SyncMethodInvoker.Invoke => <no type>.SyncInvokeRenameFile => JMMServiceImplementation.RenameFile Renaming file SKIPPED, no change From (N:\Media\Anime\Under the Dog\Under the Dog - 01 - OVA - [DameDesuYo][www][1280x720][h264][A9A1E388].mkv) to (N:\Media\Anime\Under the Dog\Under the Dog - 01 - OVA - [DameDesuYo][www][1280x720][h264][A9A1E388].mkv)

And the _FileName_ column from _VideoLocal_ table is set to an empty string.

In the **_RenameFile_** function in file _**JMMServiceImplementation.cs**_ from **_ShokoServer_**, the `name` variable is set to an empty string, and the value is modify to the new filename only when the rename is successful. `name` stay an empty string when the file rename isn't need.

I think that adding this line `name = Path.GetFileName(newFullName);`  line 8254 at the end of this block can solve the issue.
```
if (fullFileName.Equals(newFullName, StringComparison.InvariantCultureIgnoreCase))
{
  logger.Info(string.Format(
    "Renaming file SKIPPED, no change From ({0}) to ({1})",
    fullFileName, newFullName));
  ret.NewFileName = newFullName;
}
```

**Comment by ElementalCrisis** [comment]
If you preform some testing, post the results and create a PR for it.

**Comment by VadAbel** [comment]
I have sent a PR to ShokoServer

**Comment by da3dsoul** [comment]
Fixed and closed
